version: "3"
services:
  database:
    restart: always
    container_name: database
    image: mysql
    environment:
      MYSQL_DATABASE: petshop
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
    ports:
      - "6033:3306"
    healthcheck:
          test: ["CMD", "mysql", "-h", "localhost", "-P", "3306", "-u", "root", "--password=root", "-e", "select 1", "petshop"]
          interval: 1s
          timeout: 3s
          retries: 30
  app:
    build: ./
    expose:
      - "8080"
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      database:
        condition: service_healthy
